name: AutoRepair
version: '1.0'
main: me.charon.autorepair.AutoRepair
api-version: 1.18
authors: [ charon ]
description: Repairs item that player has in hand
website: charon.gq
commands:
  repair:
   description: Gives you AutoRepair anvil that you can playe anywhere and use it with plugin
